openapi: 3.0.3
info:
  title: API pro webovou aplikaci Moje_ječná
  description: |-
    Toto API slouží pro komunikaci mezi webovou aplikací a databází MojeJecna-2.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: jsesmegateplej123
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: Authentikace
    description: 'Authentikace a informace uživatelů'
  - name: Hodiny
    description: ''
  - name: Suplování
    description: ''
paths:
 /login:
  get:
    tags:
    - Authentikace
   summary: ''
   description: ''
    summary: Získání informací o uživateli podle jeho přihlašovacích údajů
    description: ''
    responses: {
        200: {
            description: 'Uživatel nalezen (vráceny data o uživateli)',
        }
    }
    parameters:
    - name: username
      in: query
      description: Uživatelské jméno
      required: true
      schema:
        type: string
    - name: password
      in: query
      description: Heslo
      required: true
      schema:
        type: string
 /hodiny:
components:
  schemas: