# Generated by Django 4.2.5 on 2023-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='MnUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=150, unique=True)),
                ('id_group', models.TextField(max_length=800)),
            ],
        ),
    ]
