# Generated by Django 4.2.5 on 2023-10-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0003_group_mnusergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnusergroup',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbModels.group'),
        ),
        migrations.AlterField(
            model_name='mnusergroup',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbModels.user'),
        ),
    ]
