# Generated by Django 4.2.5 on 2023-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0004_alter_mnusergroup_id_group_alter_mnusergroup_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
