# Generated by Django 4.2.5 on 2023-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModels', '0006_educationgroup_userclass_usertype_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
